### PR TITLE
Added support for Swift typed arrays

### PR DESCRIPTION
**Pull request by PerrchicK**
This fixes the following issue:
https://github.com/icanzilb/JSONModel/issues/398

By overriding a method called 'typedArrays()' in Swift, you’ll give the deserializer an option to deserialize the inner objects in the typed-array.

Example:
```
    override public static func typedArrays() -> [NSObject:AnyObject]! {
        return ["arrayName"    :MyTypedArray.self]
    }
```
__Note: MyTypedArray class should also subclass from JSONModel so it could be deserialized.__

### CODE REVIEW

**Comment by billinghamj** [comment]
Could you explain in some detail why this is needed, what it achieves, and link to any relevant documentation from Apple please?

**Comment by billinghamj** [comment]
Okay so it seems that this and #361 achieve the same thing in different ways - dealing with the fact that protocols don't make it through to the Obj-C runtime.

**Comment by izrie** [comment]
I agree that this is better way than #361 to support the Swift and ObjC at the same time.

**Comment by ptliddle** [comment]
Is this pull request likely to get merged anytime soon? We're making use of this functionality and so on PerrchicK's branch right now. It would be really good if this was in the main codebase.

**Comment by billinghamj** [comment]
My main concern with merging lots of changes like this is causing a bit of a mess of class methods. But we can clean those up later and focus on getting the functionality working first.

If someone writes tests to cover this, I'll marge it.

**Comment by billinghamj** [comment]
Also it needs to be expanded to work with other types - like NSDictionary, etc.

**Comment by ptliddle** [comment]
I'd be happy to do that work if we continue using JSONModel. At the moment we're currently deciding whether it make sense to continue using JSONModel as we've hit a couple other issues while using it with Swift.

**Comment by billinghamj** [comment]
@ptliddle I think in the short term, JSONModel realistically isn't the right choice for Swift projects unless you define all the models in Obj-C.

Long/medium term though, it is important to us that JSONModel adapts to work seamlessly with Swift as a first class citizen (though the library itself will continue to be written in Obj-C).

**Comment by billinghamj** [comment]
Shouldn't the changes from #346 cover this?

**Comment by PerrchicK** [comment]
You right, thanks!

**Pull request closed without merging**
