### PR TITLE
Add return value to mergeFromDictionary:useKeyMapping:error:

### LINKED ISSUE #503: Analysis of JSONModel produces warnings
Hey,

Running the static analysis tool on JSONModel produces the following warning:

`Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred`

It seems to be from JSONModel.m:1301 -
`- (void)mergeFromDictionary:(NSDictionary *)dict useKeyMapping:(BOOL)useKeyMapping error:(NSError **)error`

I'm using Xcode 7.3.1

Would be great to fix this, happy to make a PR if necessary.

### PR DESCRIPTION
**Pull request by kerrmarin**
Fixes #503

### CODE REVIEW

**Comment by billinghamj** [comment]
Couple of things:

- Were you able to actually compile & run the tests? Looks like there are some syntax errors.
- Please leave the existing tests as-is, because the existing behavior has to work too. Only add new tests.

**Comment by kerrmarin** [comment]
Hey @billinghamj,

Yes, the tests pass fine. If you point out where you believe the syntax errors to be I can change it to be a bit clearer. Also, is there a reason this project isn't using any sort of CI? That way you'd immediately know if the tests pass or not without having to check/ask.

**Comment by billinghamj** [comment]
Yeah it should be set up on Travis CI really. I just haven't gotten around to looking at it yet. Will do soon.

**Comment by billinghamj** [comment]
The issue was on this line: https://github.com/jsonmodel/jsonmodel/pull/504/commits/5ebdddd072e265a453dbf3b6fb1aa5bfe18036a9#diff-a010e5046846ce3175545b7881669106L281

I will manually merge this as it needs a bit more clean up, but looks good - should be able to get this committed shortly.

**Comment by billinghamj** [comment]
Merged as dda1a2d72630c9815917178bb0d1577f5beed169

**Comment by kerrmarin** [comment]
Awesome, thanks! 🎉

**Pull request closed without merging**
