### PR TITLE
Added millisecond support for NSDate objects

### PR DESCRIPTION
**Pull request by scottadav**
JSONModel was failing to parse NSDate values with milliseconds, for example "2013-11-27T05:00:00.000Z". I created a fork of JSONModel and made a fix, including an additional unit test case. Could you please review it and pull it into the main project if it looks good?

Thanks,
Scott

### CODE REVIEW

**Comment by milonet** [comment]
hi, i'm a big problem. The api tha i'm calling has the date formatter: 
"start_date":"2016-02-02T06:59:17.000+01:00"

how can put the value in an NSDate *start_date of JSONModel ?

**Comment by billinghamj** [comment]
Er, that format should work - it is valid in the ISO8601 spec. Is it currently rejected?

**Comment by billinghamj** [comment]
To be honest, I think we should bite the bullet and include a dependency. That's @icanzilb's call though.

**Comment by billinghamj** [comment]
Or alternatively include the files in JSONModel with some kind of prefix to prevent collision.

**Comment by billinghamj** [comment]
See #437.

**Comment by milonet** [comment]
Suppose for a moment that the format of my day is not iso8601 .. I saw the documentation you can use these methods. Where they should be placed? 

`@implementation JSONValueTransformer (CustomTransformer)

- (NSDate *)NSDateFromNSString:(NSString*)string {
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:APIDateFormat];
    return [formatter dateFromString:string];
}

- (NSString *)JSONObjectFromNSDate:(NSDate *)date {
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:APIDateFormat];
    return [formatter stringFromDate:date];
}

@end`

**Comment by billinghamj** [comment]
You could do that. The code for that can be anywhere in your project.

It might be better to use a custom setter in that case though - otherwise you're overriding NSDate serialization for every use of JSONModel in your entire project (including dependencies).

**Comment by fergalrooney** [comment]
@billinghamj Can you give an example of the custom setter you a referring to? Are you suggesting adding a custom setter on the NSDate property on the JSONModel subclass?

**Comment by billinghamj** [comment]
@fergalrooney e.g.:

```objc
- (void)setSomeDateWithNSString:(NSString *)string
{
  self.someDate = [ISO8601 parse:string];
}
```

**Comment by fergalrooney** [comment]
@billinghamj Ahhh, gotcha. So make the JSONModel property a string and add a new property for your date representation...

**Comment by billinghamj** [comment]
@fergalrooney Nope - the property doesn't need to change at all. It would still be an NSDate. JSONModel just checks whether you have some custom logic for setting the date before doing it automatically.

For completeness:

```objc
@interface MyClass

@property (nonatomic, strong) NSDate *someDate;

@end
```

```objc
@implementation MyClass

- (void)setSomeDateWithNSString:(NSString *)string
{
  self.someDate = [ISO8601 parse:string];
}

@end
```

Then to use it:

```objc
NSString *json = @"{\"someDate\": \"2016-01-01T00:00:00Z\"}";
MyClass *obj = [[MyClass alloc] initWithString:json];

// obj.someDate is now an NSDate representing 1st Jan 2016
```

**Comment by fergalrooney** [comment]
@billinghamj Fantastic. Appreciate the help!

**Pull request closed without merging**
