### PR TITLE
add more primitive types support

### PR DESCRIPTION
**Pull request by ahui2823**
support more like unsigned int , unsigned short etc...

### CODE REVIEW

**Comment by billinghamj** [comment]
Thanks! I'd like to get this merged ASAP, but I do need you to add reasonably extensive unit tests covering the use of each one of these types. This is very important to ensure no compatibility issues or regressions arise in the future.

**Comment by ahui2823** [comment]
add Unit tests for each type, and fix char convert to BOOL issues, this is unexpected.

**Comment by billinghamj** [comment]
Thanks! The commented code should be removed if no longer needed though.

It might also be worth doing a few extra checks around the cases that the commented code handled, as I'm not quite sure what it was meant to be doing.

**Comment by billinghamj** [comment]
@ahui2823 If you can sort out the couple of things I mentioned above, I can get this merged

**Comment by ahui2823** [comment]
Previous implementation is incorrect, it consider char as a BOOL structure. The property attributes of BOOL has a prefix TB, and the property attributes of char has a prefix Tc.

**Comment by billinghamj** [comment]
Thanks @ahui2823 !

**Comment by billinghamj** [comment]
@ahui2823 Looks like this change conflicts with #581 for 5th gen iPod Touch devices. Could you take a look at the other PR?

**Comment by billinghamj** [comment]
@ahui2823 Okay I think we're probably going to be rolling back this change. It seems to be causing too many issues.

**Comment by mstarke** [comment]
This merge seems to cause crashes on macOS systems #601 other issues #585

**Comment by mstarke** [comment]
A test under macOS 10.12 with 10.13 SDK yield that BOOL properties are reported as ```Tc``` ergo ```char```

**Pull request merged**
