### PR TITLE
Swift 3.0 support added to method classForCollectionProperty

### PR DESCRIPTION
**Pull request by fvvliet**
A Swift 3.0 how-to-use example is added

### CODE REVIEW

**Comment by billinghamj** [comment]
Hmm it looks like the build is failing for some reason

**Comment by fvvliet** [comment]
That's weird, such a small change. Tests run fine on my system. I have to look up what's wrong...

**Comment by fvvliet** [comment]
Found this https://github.com/travis-ci/travis-ci/issues/6675

Do you have any suggestions ?

**Comment by billinghamj** [comment]
@fvvliet Just trying to get it running again ^

**Comment by fvvliet** [comment]
I close this PR and create a new one.

**Pull request closed without merging**
